dist:
  name: otelcol-rum-dev
  description: WIP OTel Collector distribution with DDRUMReceiver
  output_path: ./otelcol-rum-dev
exporters:
  - gomod:
      # NOTE: Prior to v0.86.0 use the `loggingexporter` instead of `debugexporter`.
      go.opentelemetry.io/collector/exporter/debugexporter v0.107.0
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v0.107.0

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.107.0

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.107.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/receiver/datadogrumreceiver v1.0.0
